# Generated by Django 5.1 on 2024-08-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('fecha_publicación', models.DateField()),
                ('género', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado')], max_length=10)),
            ],
        ),
    ]
